<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>BSB托盘</AssemblyName>
    <RootNamespace>BsbTray</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <DebugType>none</DebugType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.cs" />
    <EmbeddedResource Include="..\Assets\bsb.ico" LogicalName="bsb.ico" />
  </ItemGroup>

  <PropertyGroup>
    <ApplicationIcon>..\Assets\bsb.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
